---
- hosts: localhost
  gather_facts: no
  become: no
  vars_files:
    - template_vars.yml
  tasks:
    - name: deploy config file
      template:
       src: test_template.j2
       dest: /Users/akashmainali/Desktop/Playground/output